name: search-journals-php85

services:
    php85:
        build:
            context: .
            dockerfile: ./Dockerfile-php85
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            - COMPOSER=composer.modern.json

    php85-web:
        build:
            context: .
            dockerfile: ./Dockerfile-php85
        working_dir: /app/iahx-sites/scieloorg
        volumes:
            - ./:/app
        ports:
            - "8085:8085"
        environment:
            - COMPOSER=composer.modern.json
            - SEARCH_USE_HTTPS=false
            - SEARCH_SMTP_SERVER=host.docker.internal
            - SEARCH_SMTP_PORT=1025
        command:
            - sh
            - -lc
            - cd /app && composer install --no-interaction --no-progress --working-dir=/app && cd /app/iahx-sites/scieloorg && php -S 0.0.0.0:8085 modern_router.php
