services:
    solr:
        image: solr:9.10.1
        volumes:
            - ./solr/9.10.1/cores/solrdata:/var/solr
        environment:
            - SOLR_MODULES=scripting
            - SOLR_OPTS=-XX:G1HeapRegionSize=32m -XX:InitiatingHeapOccupancyPercent=75
