name: search-journals-php85

services:
    php85:
        build:
            context: .
            dockerfile: ./Dockerfile-php85
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            - COMPOSER=composer.modern.json

    php85-web:
        build:
            context: .
            dockerfile: ./Dockerfile-php85-web
        working_dir: /app/iahx-sites/scieloorg
        ports:
            - "8085:8085"
        environment:
            - COMPOSER=composer.modern.json
            - SEARCH_USE_HTTPS=false
            - SEARCH_SOLR_CORE=solr/articles
            - SEARCH_SOLR_SERVER=host.docker.internal:8080
            - SEARCH_SMTP_SERVER=host.docker.internal
            - SEARCH_SMTP_PORT=1025
        cap_drop:
            - ALL
        security_opt:
            - no-new-privileges:true
